// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybrfwzhtjxnmkfbmcjsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlicmZ3emh0anhubWtmYm1janNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNzQ4NjIsImV4cCI6MjA2NTg1MDg2Mn0.bK3rkJNuJXlOjKc4XCZPvA1VSGA7hdgMFj6-Gb1VOgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);